import type { Metadata } from "next";
import { Noto_Sans_SC } from 'next/font/google'
import { Toaster } from 'sonner'
import { FullLoading } from '@/components/full-loading'
import "./globals.css";

// 配置思源黑体
const notoSansSC = Noto_Sans_SC({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansSC.className} antialiased h-screen`}
      >
        <Toaster />

        {children}
        <FullLoading />
      </body>
    </html>
  );
}
